Update package version for DAOS API major version bump
daos-stack/testmpio pull request #5
Opened 2020-12-15 03:32 UTC by kccain

PR-repos: daos@PR-3935:14
PR-repos: mpich@PR-44:2

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

2020-12-15 04:37 UTC, brianjmurrell commented
Update the `packaging/` subdir before trying to go any further.

2021-01-07 17:39 UTC, brianjmurrell requested changes
Is this another package that doesn't have a direct dependency on `libdaos,so` and therefore unaffected by a version bump in it?

2021-01-07 17:39 UTC, brianjmurrell commented on packaging/Dockerfile.centos.7
> +# Copyright 2018-2020, Intel Corporation
```suggestion
# Copyright 2018-2021, Intel Corporation
```
now.

2021-01-07 17:39 UTC, brianjmurrell commented on packaging/Dockerfile.ubuntu.20.04
> +# Copyright 2019-2020, Intel Corporation
```suggestion
# Copyright 2019-2021, Intel Corporation
```

2021-01-07 17:56 UTC, kccain commented
Does the fact that it depends on mpich (that itself has changed due to a dependency on the new libdaos API) have relevance? And then that it provides a package that daos (Jenkinsfile) requires when it provisions packages on nodes for testing?

2021-01-07 18:10 UTC, brianjmurrell commented
> Does the fact that it depends on mpich (that itself has changed due to a dependency on the new libdaos API) have relevance?

Only if the ABI of mpich changed, which I don't think it did, did it?

> And then that it provides a package that daos (Jenkinsfile) requires when it provisions packages on nodes for testing?

So this is a provides/requires that probably ought not exist.  Frankly none of the virtual provides/requires probably needs to exist for anything.  RPM automatically detects library (including) version dependencies.  I was in fact going to experiment with getting rid of them altogether at some future date and had it in my mind to have you get rid of them in your PRs but didn't want to burden your effort with that.

But if this tool doesn't actually need to be rebuilt, we should get rid of the virtual provides/requires for it and just use the actual package name as the dependency in the DAOS `Jenkinsfile`.

2021-01-23 01:11 UTC, kccain commented
This PR is not needed, closing.

2021-01-23 01:11 UTC, closed without merging